### ISSUE TITLE
インストールページが開けない

### ISSUE THREAD

**Issue by mt8** [mt8/wbkobe77#2]
/wp-admin/wp-install.php
```
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; 
wpdb has a deprecated constructor in /var/www/public/b2-include/wp-db.php on line 18

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/public/b2-include/wp-db.php:30 Stack trace: 
#0 /var/www/public/b2-include/wp-db.php(397): wpdb->wpdb('***', '***', '***', '***') 
#1 /var/www/public/b2config.php(337): require_once('/var/www/public...') 
#2 /var/www/public/wp-admin/wp-install.php(2): require('/var/www/public...') 
#3 {main} thrown in /var/www/public/b2-include/wp-db.php on line 30
```

**Comment by mt8** [comment]
see #4 #5 #7
