### ISSUE TITLE
0.71-goldからのアップグレードができない

### ISSUE THREAD

**Issue by mt8** [mt8/wbkobe77#36]
/wp-admin/upgrade.php

```
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; wpdb has a deprecated constructor in /var/www/public/wp-includes/wp-db.php on line 19

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/public/wp-includes/wp-db.php:32 Stack trace: #0 /var/www/public/wp-includes/wp-db.php(411): wpdb->wpdb('***', '***', '***', '***') #1 /var/www/public/wp-settings.php(24): require('/var/www/public...') #2 /var/www/public/wp-config.php(25): require_once('/var/www/public...') #3 /var/www/public/wp-admin/upgrade.php(4): require('/var/www/public...') #4 {main} thrown in /var/www/public/wp-includes/wp-db.php on line 32
```

**Comment by mt8** [comment]
https://github.com/mt8/wbkobe77/tree/1.0-platinum

**Comment by mt8** [comment]
以下のSQLを実行しないといけない

```
update b2options set option_value = 'http://wordpress.test' where option_id = 1;
```
